baseurl = "/"
title = "Developmental Datascience"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "Mainroad"
disqusShortname = "developmentaldatascience" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[Author]
    name = "Caspar van Lissa"
    bio = "Interdisciplinary social scientist and datascience dilletante."
    avatar = "img/caspar.png"


[Params]
    subtitle = "Caspar van Lissa" # Subtitle of your site
    description = "Blog about science and syntax" # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["post"]
	  RSSSections = [ "posts"]

	[params.logo]
		logo_url = "developmentaldatascience.png"

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
	# Enable "Social" widget, if any of "social_*" set a value
    social_twitter = "cjvanlissa"
    social_github = "cjvanlissa"
    social_email = "c.j.vanlissa@uu.nl"
	
[[menu.main]]        
    name = "R blogs"
    weight = -120
    identifier = "R"
    url = "/categories/r"
	
[[menu.main]]        
    name = "Teaching tales"
    weight = -120
    identifier = "story"
    url = "/categories/story"