baseurl = "/"
title = "Developmental Datascience"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "Mainroad"
disqusShortname = "developmentaldatascience" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Author]
    name = "dr. Caspar van Lissa"
    bio = "Interdisciplinary social scientist and datascience dilletante."
    avatar = "img/caspar.png"


[Params]
    subtitle = "dr. Caspar van Lissa" # Subtitle of your site
    description = "Blog about science and syntax" # Description of your site
    comments = true
    opengraph = true
    twitter_cards = true # Enable Twitter Cards if true
    readmore = false # Show "Read more" button in list if true
    authorbox = true
    post_navigation = true
    post_meta = ["date", "categories"] # Order of post meta information
    dateformat = "2006-01-02" # Change the format of dates
    mathjax = true # Enable MathJax
    mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
    mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config

	[params.logo]
		logo_url = "developmentaldatascience.png"
		
[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "social", "taglist"]

[Params.widgets]
    recent_num = 10 # Set the number of articles in the "Recent articles" widget
    tags_counter = true # Enable counter for each tag in "Tags" widget
    social_rss = "RSS feed"
    
[Params.widgets.social]
  # Enable parts of social widget
  twitter = "cjvanlissa"
  linkedin = "caspar-lissa-36749b46"
  github = "cjvanlissa"
  email = "c.j.vanlissa@uu.nl"
  social_rss = "RSS feed"
