---
title: "Using GitBooks to create Open course materials"
author: "Caspar van Lissa"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
categories: ["R", "Open Science"]
tags: ["open science", "git", "bookdown", "rmarkdown"]
bibliography: [bibliography.bib]
link-citations: true
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
mplus_output <- c("FINAL CLASS COUNTS AND PROPORTIONS FOR EACH LATENT CLASS VARIABLE",
"BASED ON THE ESTIMATED MODEL",
"",
"  Latent Class",
"    Variable    Class",
"",
"    C1             1       525.87720          0.26294",
"                   2       749.33826          0.37467",
"                   3       724.78455          0.36239",
"    C2             1       391.52097          0.19576",
"                   2      1132.59033          0.56630",
"                   3       475.88873          0.23794",
"")
```

With the social restrictions put in place to combat the COVID-19 virus, many teachers are scrambling to transition their courses to online formats. One tool that can be very useful in this context, is the so-called *GitBook*. It is an oline "book" format, that can be hosted directly from a GitHub repository. I have some prior expertise benefiting from the advantages of using a GitBook, because I transitioned a course from proprietary software to R last year. [Here is a GitBook I made about how to make a GitBook for Open Educational Materials](https://cjvanlissa.github.io/gitbook-demo/).

## Why use a GitBook for teaching?

### To spead the workload

My challenge was that I had to translate all tutorial instructions from proprietary software to R, and there was not enough time to complete this task before the course commenced. By making the tutorial instructions available in [this GitBook](https://cjvanlissa.github.io/TCSM/), I was able to continue translating tutorial instructions *while the semester was ongoing*, and push updates to GitHub in time for each session, which were immediately available to all students. The parallel with the current situation is that some courses are now forced to start teaching in an online format, without having enough time to completely prepare. By using a GitBook, you can spread out the workload of preparing your materials across the semester. [This is the finished GitBook](https://cjvanlissa.github.io/TCSM/)

### To contribute or use existing Open Educational Materials
Another key advantage of using a GitBook is, that you can easily make your course materials available for others to use under an open access license, or perhaps you can use an existing GitBook from the internet and adapt it for your own uses. GitBooks can be easily duplicated and adapted, just like any other project hosted on GitHub. Contributing Open Educational Materials can help reduce the workload on teachers around the world, and can improve the quality of the materials used thanks to online collaborating and feedback.

### To benefit from formatting advantages

GitBooks also have two formatting advantages over classic PDF or Word files. First, they are Rmarkdown files, and can thus include blocks of R ([or Python](https://rstudio.github.io/reticulate/articles/r_markdown.html)) code that can be evaluated, and whose results are rendered to the file. Second, they are interactive web pages, and as such, can have dynamic features (such as answers to assignments that can be hidden, or boxes where students can fill out an answer to be checked). Additionally, other web pages or interactive apps can be embedded within the page. So whereas a traditional document is static, GitBooks can be interactive.

## How do GitBooks work?

I will focus specifically on GitBooks that are made in [Rstudio](www.rstudio.com), using the [`rmarkdown` markup language](https://rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf), rendered using the [`bookdown` package](https://bookdown.org/yihui/bookdown/get-started.html), and hosted on [GitHub](https://github.com/). [Here is an example of such a book](https://cjvanlissa.github.io/gitbook-demo/).

These GitBooks consist of an Rstudio project, with several Rmarkdown files containing the chapters of the book. Inside Rstudio, users can press a "Build Book" button, which renders all of these chapters to a nicely formatted HTML book (and a PDF file for users to download). Users can push the finished book to a GitHub repository, and indicate on GitHub that the book should be hosted on GitHub pages. Voilà!

## Getting started yourself

If you are convinced that this tool might benefit your teaching, I have prepared some materials to get you started. [This is an educational GitBook about making an educational GitBook.](https://cjvanlissa.github.io/gitbook-demo/). I made it as course material for the first [OSCoffee session](https://openscience-utrecht.com/oscoffee/), next Friday April 3d. The OSCoffee sessions are brief educational sessions or discussions hosted by the [Open Science Community Utrecht](https://openscience-utrecht.com) during the COVID-19 shutdown, to keep inspiring our support base throughout the Summer period!